
package com.dream.models;

public enum StudyLevels {
	KG1, KG2, PRIMARY1, PRIMARY2, PRIMARY3, PRIMARY4, PRIMARY5, PRIMARY6, PREPARATORY1, PREPARATORY2, PREPARATORY3,
	SECONDRY1, SECONDRY2, SECONDRY3, NA, OTHER
}
